gems: [bourbon, neat, bitters]

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

  # js_compressor:  uglifier
  # css_compressor: sass
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    #- _vendors/bootstrap/stylesheets
    #- _vendors/bootstrap/javascripts
# Site settings
title: Stokes Drift
description: Service platform for the modern world

# Name of project on Github
baseurl:

# Build settings
markdown: kramdown